version: '3.8'

services:
  # IL NOSTRO SERVER PHP
  web:
    build: .
    ports:
      - "8080:80" # L'app sarà visibile su http://localhost:8080
    depends_on:
      - db

  # IL DATABASE MYSQL
  db:
    image: mariadb:10.6
    restart: always
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs: 
      - /tmp
      - /var/run/mysqld
      - /var/cache/mariadb

    environment:
      # Impostiamo le credenziali base per il DB
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: goof
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"