name: "IaC Security - Checkov"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write # Fondamentale per caricare gli alert nella tab Security

jobs:
  checkov:
    name: Checkov Scan
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@3203f966a7ccd680cd8f6aaa3c3c5b0b3e9afa32 # master
        with:
          directory: .
          # Diciamo a Checkov di guardare il Dockerfile e i file di GitHub Actions
          framework: dockerfile,github_actions 
          # Vogliamo l'output sia in console per leggerlo, sia in SARIF per GitHub
          output_format: cli,sarif
          output_file_path: console,results.sarif
          # soft_fail: true # Decommenta questa riga se non vuoi che l'errore blocchi la build

      - name: Carica i risultati su GitHub Security
        uses: github/codeql-action/upload-sarif@ce64ddcb0d8d890d2df4a9d1c04ff297367dea2a # v3.35.2
        if: always() # Esegue l'upload anche se Checkov trova degli errori
        with:
          sarif_file: results.sarif