name: "Lint - Hadolint (Docker)"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  hadolint:
    name: Hadolint Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Esegui Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          # Facciamo in modo che sputi i risultati anche nel pannello delle annotazioni di GitHub
          format: sarif
          output-file: hadolint.sarif
          failure-threshold: error

      - name: Carica i risultati su GitHub Security
        uses: github/codeql-action/upload-sarif@v4 
        if: always()
        with:
          sarif_file: hadolint.sarif